name: Release

on:
  release:
    types:
      - released

permissions:
  contents: write

jobs:
  release-binaries:
    uses: ./.github/workflows/reusable-build-binaries.yml
    with:
      snapshot: false  # Release mode
      ref: ${{ github.ref }}
      upload-artifacts: true
    permissions:
      contents: write

  release-docker-images:
    needs: release-binaries
    uses: ./.github/workflows/reusable-build-docker-images.yml
    with:
      ref: ${{ github.ref }}
      image-tag: ${{ github.ref_name }}
      upload-artifact: true
      push-to-registry: true
      tag-latest: true
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
